# Generated by Django 4.1.3 on 2022-11-18 16:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=128)),
                ('last_name', models.CharField(max_length=128)),
                ('email', models.CharField(max_length=128)),
                ('password', models.CharField(max_length=128)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Student',
                'verbose_name_plural': 'Students',
            },
        ),
        migrations.CreateModel(
            name='SelectedFood',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('breakfast1', models.CharField(choices=[('IDLI-SAMBAR', 'Idli-Sambar'), ('PUTTU-KADALA', 'Puttu-Kadala'), ('APPAM-STEW', 'Appam-Stew')], max_length=64)),
                ('lunch1', models.CharField(choices=[('BIRIYANI', 'Biriyani'), ('RICE-CURRY', 'Rice-curry'), ('KANJI', 'Kanjis')], max_length=64)),
                ('snacks1', models.CharField(choices=[('TEA', 'Tea'), ('COFFE', 'Coffe'), ('PUFFS', 'Puffs')], max_length=64)),
                ('supper1', models.CharField(choices=[('CHAPPATHI-CHICKEN', 'Chappathi-Chicken'), ('POORI-CURRY', 'Poori-Curry'), ('MASALA-DOSA', 'Masala Dosa')], max_length=64)),
                ('date1', models.DateField()),
                ('breakfast2', models.CharField(choices=[('IDLI-SAMBAR', 'Idli-Sambar'), ('PUTTU-KADALA', 'Puttu-Kadala'), ('APPAM-STEW', 'Appam-Stew')], max_length=64)),
                ('lunch2', models.CharField(choices=[('BIRIYANI', 'Biriyani'), ('RICE-CURRY', 'Rice-curry'), ('KANJI', 'Kanjis')], max_length=64)),
                ('snacks2', models.CharField(choices=[('TEA', 'Tea'), ('COFFE', 'Coffe'), ('PUFFS', 'Puffs')], max_length=64)),
                ('supper2', models.CharField(choices=[('CHAPPATHI-CHICKEN', 'Chappathi-Chicken'), ('POORI-CURRY', 'Poori-Curry'), ('MASALA-DOSA', 'Masala Dosa')], max_length=64)),
                ('date2', models.DateField()),
                ('breakfast3', models.CharField(choices=[('IDLI-SAMBAR', 'Idli-Sambar'), ('PUTTU-KADALA', 'Puttu-Kadala'), ('APPAM-STEW', 'Appam-Stew')], max_length=64)),
                ('lunch3', models.CharField(choices=[('BIRIYANI', 'Biriyani'), ('RICE-CURRY', 'Rice-curry'), ('KANJI', 'Kanjis')], max_length=64)),
                ('snacks3', models.CharField(choices=[('TEA', 'Tea'), ('COFFE', 'Coffe'), ('PUFFS', 'Puffs')], max_length=64)),
                ('supper3', models.CharField(choices=[('CHAPPATHI-CHICKEN', 'Chappathi-Chicken'), ('POORI-CURRY', 'Poori-Curry'), ('MASALA-DOSA', 'Masala Dosa')], max_length=64)),
                ('date3', models.DateField()),
                ('breakfast4', models.CharField(choices=[('IDLI-SAMBAR', 'Idli-Sambar'), ('PUTTU-KADALA', 'Puttu-Kadala'), ('APPAM-STEW', 'Appam-Stew')], max_length=64)),
                ('lunch4', models.CharField(choices=[('BIRIYANI', 'Biriyani'), ('RICE-CURRY', 'Rice-curry'), ('KANJI', 'Kanjis')], max_length=64)),
                ('snacks4', models.CharField(choices=[('TEA', 'Tea'), ('COFFE', 'Coffe'), ('PUFFS', 'Puffs')], max_length=64)),
                ('supper4', models.CharField(choices=[('CHAPPATHI-CHICKEN', 'Chappathi-Chicken'), ('POORI-CURRY', 'Poori-Curry'), ('MASALA-DOSA', 'Masala Dosa')], max_length=64)),
                ('date4', models.DateField()),
                ('breakfast5', models.CharField(choices=[('IDLI-SAMBAR', 'Idli-Sambar'), ('PUTTU-KADALA', 'Puttu-Kadala'), ('APPAM-STEW', 'Appam-Stew')], max_length=64)),
                ('lunch5', models.CharField(choices=[('BIRIYANI', 'Biriyani'), ('RICE-CURRY', 'Rice-curry'), ('KANJI', 'Kanjis')], max_length=64)),
                ('snacks5', models.CharField(choices=[('TEA', 'Tea'), ('COFFE', 'Coffe'), ('PUFFS', 'Puffs')], max_length=64)),
                ('supper5', models.CharField(choices=[('CHAPPATHI-CHICKEN', 'Chappathi-Chicken'), ('POORI-CURRY', 'Poori-Curry'), ('MASALA-DOSA', 'Masala Dosa')], max_length=64)),
                ('date5', models.DateField()),
                ('breakfast6', models.CharField(choices=[('IDLI-SAMBAR', 'Idli-Sambar'), ('PUTTU-KADALA', 'Puttu-Kadala'), ('APPAM-STEW', 'Appam-Stew')], max_length=64)),
                ('lunch6', models.CharField(choices=[('BIRIYANI', 'Biriyani'), ('RICE-CURRY', 'Rice-curry'), ('KANJI', 'Kanjis')], max_length=64)),
                ('snacks6', models.CharField(choices=[('TEA', 'Tea'), ('COFFE', 'Coffe'), ('PUFFS', 'Puffs')], max_length=64)),
                ('supper6', models.CharField(choices=[('CHAPPATHI-CHICKEN', 'Chappathi-Chicken'), ('POORI-CURRY', 'Poori-Curry'), ('MASALA-DOSA', 'Masala Dosa')], max_length=64)),
                ('date6', models.DateField()),
                ('breakfast7', models.CharField(choices=[('IDLI-SAMBAR', 'Idli-Sambar'), ('PUTTU-KADALA', 'Puttu-Kadala'), ('APPAM-STEW', 'Appam-Stew')], max_length=64)),
                ('lunch7', models.CharField(choices=[('BIRIYANI', 'Biriyani'), ('RICE-CURRY', 'Rice-curry'), ('KANJI', 'Kanjis')], max_length=64)),
                ('snacks7', models.CharField(choices=[('TEA', 'Tea'), ('COFFE', 'Coffe'), ('PUFFS', 'Puffs')], max_length=64)),
                ('supper7', models.CharField(choices=[('CHAPPATHI-CHICKEN', 'Chappathi-Chicken'), ('POORI-CURRY', 'Poori-Curry'), ('MASALA-DOSA', 'Masala Dosa')], max_length=64)),
                ('date7', models.DateField()),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.students')),
            ],
            options={
                'verbose_name': 'Selected Food',
                'verbose_name_plural': 'Selected Food',
            },
        ),
    ]
